*** Settings ***
Library    SeleniumLibrary

*** Variables ***

#Dados para o teste
${e-mail_profissional}               testeautomacao@robot.com
${primeiro_nome}                     tAutomacao
${segundo_nome}                      Robot
${empresa}                           testeAutomacao
${ddd}                               12
${numero}                            123456789
${senha}                             123456